package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionAlertasIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionUsuariosInt.idl
* viernes 20 de marzo de 2020 05:45:47 PM COT
*/

public interface GestionAlertasIntOperations 
{
  void registrarPaciente (servidorDeAlertas.sop_corba.PacienteDTO objPaciente, org.omg.CORBA.BooleanHolder resultado);
  boolean enviarIndicadores (servidorDeAlertas.sop_corba.PacienteDTO objPaciente, org.omg.CORBA.BooleanHolder resultado);
} // interface GestionAlertasIntOperations
