package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionAlertasIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionUsuariosInt.idl
* sábado 21 de marzo de 2020 08:59:52 PM COT
*/

abstract public class GestionAlertasIntHelper
{
  private static String  _id = "IDL:sop_corba/GestionAlertasInt:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorDeAlertas.sop_corba.GestionAlertasInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorDeAlertas.sop_corba.GestionAlertasInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (servidorDeAlertas.sop_corba.GestionAlertasIntHelper.id (), "GestionAlertasInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorDeAlertas.sop_corba.GestionAlertasInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionAlertasIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorDeAlertas.sop_corba.GestionAlertasInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static servidorDeAlertas.sop_corba.GestionAlertasInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servidorDeAlertas.sop_corba.GestionAlertasInt)
      return (servidorDeAlertas.sop_corba.GestionAlertasInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servidorDeAlertas.sop_corba._GestionAlertasIntStub stub = new servidorDeAlertas.sop_corba._GestionAlertasIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static servidorDeAlertas.sop_corba.GestionAlertasInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servidorDeAlertas.sop_corba.GestionAlertasInt)
      return (servidorDeAlertas.sop_corba.GestionAlertasInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servidorDeAlertas.sop_corba._GestionAlertasIntStub stub = new servidorDeAlertas.sop_corba._GestionAlertasIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
