package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionUsuariosInt.idl
* viernes 20 de marzo de 2020 05:45:47 PM COT
*/

public final class PacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numHabitacion = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public String estrato = null;
  public int edad = (int)0;
  public int frecuenciaCardiaca = (int)0;
  public int presionArterial = (int)0;
  public int frecuenciaRespiratoria = (int)0;
  public int saturacionOxigeno = (int)0;
  public int sistolica = (int)0;
  public int diastolica = (int)0;
  public String temperatura = null;
  public servidorDeAlertas.sop_corba.PacienteCllbckInt pacbck = null;

  public PacienteDTO ()
  {
  } // ctor

  public PacienteDTO (int _numHabitacion, String _nombres, String _apellidos, String _estrato, int _edad, int _frecuenciaCardiaca, int _presionArterial, int _frecuenciaRespiratoria, int _saturacionOxigeno, int _sistolica, int _diastolica, String _temperatura, servidorDeAlertas.sop_corba.PacienteCllbckInt _pacbck)
  {
    numHabitacion = _numHabitacion;
    nombres = _nombres;
    apellidos = _apellidos;
    estrato = _estrato;
    edad = _edad;
    frecuenciaCardiaca = _frecuenciaCardiaca;
    presionArterial = _presionArterial;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    saturacionOxigeno = _saturacionOxigeno;
    sistolica = _sistolica;
    diastolica = _diastolica;
    temperatura = _temperatura;
    pacbck = _pacbck;
  } // ctor

} // class PacienteDTO
