package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionUsuariosInt.idl
* sábado 21 de marzo de 2020 08:59:52 PM COT
*/

public interface PacienteCllbckIntOperations 
{
  String notificarPaciente (String mensaje);
} // interface PacienteCllbckIntOperations
