package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GestionUsuariosInt.idl
* s�bado 21 de marzo de 2020 08:59:52 PM COT
*/

public final class PacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numHabitacion = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public float edad = (float)0;
  public float frecuenciaCardiaca = (float)0;
  public float presionArterial = (float)0;
  public float frecuenciaRespiratoria = (float)0;
  public float saturacionOxigeno = (float)0;
  public float sistolica = (float)0;
  public float diastolica = (float)0;
  public float temperatura = (float)0;
  public servidorDeAlertas.sop_corba.PacienteCllbckInt pacbck = null;

  public PacienteDTO ()
  {
  } // ctor

  public PacienteDTO (int _numHabitacion, String _nombres, String _apellidos, float _edad, float _frecuenciaCardiaca, float _presionArterial, float _frecuenciaRespiratoria, float _saturacionOxigeno, float _sistolica, float _diastolica, float _temperatura, servidorDeAlertas.sop_corba.PacienteCllbckInt _pacbck)
  {
    numHabitacion = _numHabitacion;
    nombres = _nombres;
    apellidos = _apellidos;
    edad = _edad;
    frecuenciaCardiaca = _frecuenciaCardiaca;
    presionArterial = _presionArterial;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    saturacionOxigeno = _saturacionOxigeno;
    sistolica = _sistolica;
    diastolica = _diastolica;
    temperatura = _temperatura;
    pacbck = _pacbck;
  } // ctor

    public PacienteDTO(int numHabitacion, String nombre, String apellido, float edad,servidorDeAlertas.sop_corba.PacienteCllbckInt _pacbck) {
       this.numHabitacion = numHabitacion;
       this.nombres = nombre;
       this.apellidos = apellido;
       this.edad = edad;
        pacbck = _pacbck;
    }

} // class PacienteDTO
