package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificacionesInt.idl
* sábado 21 de marzo de 2020 08:59:57 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void notificarAlMedico (servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
