package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;

import ServidorNotificaciones.dto.ClsIndicadoresAlerta;
import ServidorNotificaciones.dto.ClsIndicadoresRegistros;
import java.util.ArrayList;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificacionesInt.idl
* s�bado 21 de marzo de 2020 08:59:57 PM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numeroHabitacion = (int)0;
  public float edad = (float)0;
  public String nombres = null;
  public String apellidos = null;
  public String mensajeAlMedico = null;
  public String fecha = null;
  public String hora = null;
  public  ArrayList<ClsIndicadoresAlerta> listaIndicadoresAlerta = new ArrayList<>();
  public ArrayList<ClsIndicadoresRegistros> listaIndicadoresRegistros = new ArrayList<>();

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (int _numeroHabitacion, float _edad, String _nombres, String _apellidos, String _mensajeAlMedico, String _fecha, String _hora)
  {
    numeroHabitacion = _numeroHabitacion;
    edad = _edad;
    nombres = _nombres;
    apellidos = _apellidos;
    mensajeAlMedico = _mensajeAlMedico;
    fecha = _fecha;
    hora = _hora;
    
  } // ctor

    public ArrayList<ClsIndicadoresAlerta> getListaIndicadoresAlerta() {
        return listaIndicadoresAlerta;
    }

    public void setListaIndicadoresAlerta(ArrayList<ClsIndicadoresAlerta> listaIndicadoresAlerta) {
        this.listaIndicadoresAlerta = listaIndicadoresAlerta;
    }

    public ArrayList<ClsIndicadoresRegistros> getListaIndicadoresRegistros() {
        return listaIndicadoresRegistros;
    }

    public void setListaIndicadoresRegistros(ArrayList<ClsIndicadoresRegistros> listaIndicadoresRegistros) {
        this.listaIndicadoresRegistros = listaIndicadoresRegistros;
    }

  
} // class ClsMensajeNotificacionDTO
