package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotificacionesInt.idl
* viernes 20 de marzo de 2020 05:49:38 PM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numeroHabitacion = (int)0;
  public int edad = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public String estrato = null;
  public String mensajeAlMedico = null;
  public String fecha = null;
  public String hora = null;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (int _numeroHabitacion, int _edad, String _nombres, String _apellidos, String _estrato, String _mensajeAlMedico, String _fecha, String _hora)
  {
    numeroHabitacion = _numeroHabitacion;
    edad = _edad;
    nombres = _nombres;
    apellidos = _apellidos;
    estrato = _estrato;
    mensajeAlMedico = _mensajeAlMedico;
    fecha = _fecha;
    hora = _hora;
  } // ctor

} // class ClsMensajeNotificacionDTO
