
module sop_corba { 
    interface GestionNotificaciones{
        struct ClsMensajeNotificacionDTO{
	    	long numeroHabitacion;
     		long edad;
     		string nombres, apellidos, estrato, mensajeAlMedico;
     		string fecha, hora;
	};
	void notificarAlMedico(in ClsMensajeNotificacionDTO objNotificacion);
    }; 
};